version: '3.8'

services:
  web:
    build:
       context: ./test_images
       dockerfile: Dockerfile
    command: gunicorn test_images.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/test_images/static
      - media_volume:/usr/src/test_images/media
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/test_images/static
      - media_volume:/usr/src/test_images/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume: