version: '3.8'

services:
  web:
    build: ./test_images
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test_images/:/usr/src/test_images/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_volume: